# Используем официальный образ Python
FROM python:3.10-slim

# Указываем рабочую папку внутри контейнера
WORKDIR /app

# Копируем файл со списком библиотек и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем ВСЕ файлы вашего бота внутрь контейнера
COPY . .

# Команда для запуска бота
CMD ["python", "main.py"]